### ISSUE TITLE
[QA] admin user gets disabled, when user limit is reached

### ISSUE THREAD

**Issue by jnweiger** [owncloud/qnap#33]
Seen with ownCloud for QNAP 10.8.0 from `ownCloud_10.8.0_arm-x41.qpkg` (dated 2021-07-27)

Intentionally enabled 7 users while only a 5 user license was active

A minute later the admin user got logged out :-(

![image](https://user-images.githubusercontent.com/1108546/127186781-37ad3c56-689d-4fbb-88eb-6062ab50c63d.png)

```
root@e642b8e5209a: /var/www/owncloud # occ user:list -a enabled -a lastLogin -a email
  - admin:
    - enabled: false
    - lastLogin: 1627400695
    - email: qnap-admin@example.com
  - jw@owncloud.com:
    - enabled: true
    - lastLogin: 1627392401
    - email: jw@owncloud.com
  - user1:
    - enabled: true
    - lastLogin: 0
    - email: user1@ex.hop
  - user2:
    - enabled: false
    - lastLogin: 0
    - email: user2@ex.mail
  - user3:
    - enabled: true
    - lastLogin: 1627342138
    - email: user3@mail.org
  - user4:
    - enabled: true
    - lastLogin: 1627342197
    - email: user4@mail.org
  - user5:
    - enabled: true
    - lastLogin: 0
    - email: user5@mail.com
  - user6:
    - enabled: true
    - lastLogin: 1627342285
    - email: u6@ex
```
